#!/bin/zsh

alias free='free -m'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias ls='exa --color=auto --group-directories-first'
alias lst='ls --tree'
alias la='ls --all'
alias ll='ls --all --long --header --group'
alias llt='ll --tree'
alias tree='ls --tree'

alias cdtemp='cd `mktemp -d`'

alias cp='cp -iv'
alias ln='ln -v'
alias mkdir='mkdir -vp'
alias mv='mv -iv'
alias rm='rm -Iv'

alias dh='du -h'
alias df='df -h'

alias su='sudo -E su -m'

alias sysu='systemctl --user'
alias jnsu='journalctl --user'
alias svim='sudoedit'

alias blkdiscard='(echo -n "Are you sure? "; read) && blkdiscard'

# Use ripgrep instead of grep
alias grep='rg'
# Use bat instead of cat
alias cat='bat'

alias zreload='export ZSH_RELOADING_SHELL=1; source $ZDOTDIR/.zshenv; source $ZDOTDIR/.zshrc; source $ZDOTDIR/zaliases; unset ZSH_RELOADING_SHELL'
alias zedit='$EDITOR $ZDOTDIR/.zshrc'
alias zaliases='$EDITOR $ZDOTDIR/zaliases'
alias zenv='$EDITOR $ZDOTDIR/.zshenv'
