#!/bin/zsh

alias cp="cp -i"
alias free='free -m'
alias ls='ls --color=auto -h'
alias la='ls -A'
alias ll='ls -AFl'
alias dh='du -h'
alias df='df -h'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias sysu='systemctl --user'
alias svim='sudoedit'

alias zreload='source $ZDOTDIR/.zshenv; source $ZDOTDIR/.zshrc; source $ZDOTDIR/zaliases'
alias zedit='$EDITOR $ZDOTDIR/.zshrc'
alias zaliases='$EDITOR $ZDOTDIR/zaliases'
alias zenv='$EDITOR $ZDOTDIR/.zshenv'

