{ pkgs, ... }:

let
  zshenv-local = pkgs.writeScript "zshenv.local" ''
      #!${pkgs.zsh}/bin/zsh
      # Generated by NixOS
      export XDG_CONFIG_HOME=''${XDG_CONFIG_HOME:-$HOME/.config}
      export XDG_DATA_HOME=''${XDG_DATA_HOME:-$HOME/.local/share}
      export XDG_CACHE_HOME=''${XDG_CACHE_HOME:-$HOME/.cache}
      export ZDOTDIR=''${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}
  '';
  zshenv = pkgs.runCommand "zshenv" {
    outputsToInstall = [ "etc" ];
  } ''
    mkdir -p $out/etc
    cp -v ${zshenv-local} $out/etc/zshenv.local
  '';
in
{
  environment.systemPackages = [ zshenv ];
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestions.enable = true;
    syntaxHighlighting.enable = true;
  };
}
